version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: cart-service
    restart: always
    environment:
      MYSQL_DATABASE: cart-service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
